### PR TITLE
fixed modal appearance

### LINKED ISSUE #127: Coordinator Dashboard: modal appearance is kind of broken
time goes over and writes over the other columns, perhaps we can have the left green arrow on the side of everything?  either that, or have the left column be organization + contact info, and the right column be just all the information (addr, description, time, etc).

not sure if this was broken before, i might have broken it when i changed the food description model :'(

### PR DESCRIPTION
**Pull request by nikitr**
Fixed #127 but there is no content showing up

### CODE REVIEW

**Comment by jjwon** [comment]
screen shot 2015-04-30 at 16 09 45

Is this the intended look?  It looks quite messy to me still.

I made a really crappy mockup with Photoshop.  The main goal with this is clarity and organization.  As long as it looks organized and clean in some meaningful way, that'd be great.

screen shot 2015-04-30 at 16 09 45

**Comment by nikitr** [comment]
I think I fixed the wrong thing, sorry! I will work on editing the appearance. Thanks.

**Comment by nikitr** [comment]
Let me know if it looks better now/if I should change anything.

**Comment by nikitr** [comment]
Modal appearance should be correct now!

**Comment by nikitr** [comment]
Reverted to what was there before merge conflict

**Pull request merged**
