### PR TITLE
fix date format

### LINKED ISSUE #123: Coordinator Dashboard: time is displayed kinda funny on coordinator dash
should convert this to make it more human-readable

### PR DESCRIPTION
**Pull request by nikitr**
Fixed #123

### CODE REVIEW

**Comment by jjwon** [comment]
instead of adding moment.js (3k line js file) just for this specific task, take a look at modifying the donation object before we pass it into gon (check out coordinator_controller, in schedule)

**Comment by nikitr** [comment]
fixed without moment.js

**Comment by nikitr** [comment]
added end time clock and fixed some more formatting

**Comment by nikitr** [comment]
formatted all start and end times

**Pull request merged**
