### PR TITLE
Jason/post pres fixes

### PR DESCRIPTION
**Pull request by jjwon**
Fix a ton of bugs that we found from doing today's presentation.  I think after this, all that we pretty much need to do it one last test, write documentation, and then we're ready for a hand-off!

The last huge bug that remains is that :warning:  **donation picture uploads mysteriously stopped working** :warning:  I have no clue why it doesn't work (especially since the code looks more or less the same).

@akakitani can you please try pulling this branch and see if pictures are being uploaded at all?  When I look at the params posted in the server logs, there is just straight up no picture being sent.  I think this is the cause of the picture not being attached correctly in the emails.

If you can't figure it out maybe we can bother Sam, Howard, Warren, or another Rails beast ;___;

### CODE REVIEW

**Comment by jjwon** [comment]
@chenhoward @SamLau95 any thoughts :'(

**Comment by chenhoward** [comment]
If I find ze time tmmr I'll take a look at it!  Been kinda swamped with starting to shtudy LOL

**Comment by jjwon** [comment]
FIXED YEEE

**Comment by chenhoward** [comment]
Noice!

**Pull request merged**
